#include "sbfs.h"
#include "block.h"
#include "memory.h"
#include "uart.h"
#include <stdint.h>
static sbfs_superblock_t superblock;
static int mounted;
static int read_inode(uint32_t number, sbfs_inode_t *inode) { if (!mounted || number == 0 || number >= superblock.inode_count || inode == 0) return -1; uint8_t sector[SBFS_BLOCK_SIZE]; uint64_t location = SBFS_BASE_SECTOR + superblock.inode_table_start + number / SBFS_INODES_PER_SECTOR; if (block_read(location, sector) != 0) return -1; memcpy(inode, sector + (number % SBFS_INODES_PER_SECTOR) * SBFS_INODE_SIZE, sizeof(*inode)); return 0; }
static int write_inode(uint32_t number, const sbfs_inode_t *inode) { uint8_t sector[SBFS_BLOCK_SIZE]; uint64_t location = SBFS_BASE_SECTOR + superblock.inode_table_start + number / SBFS_INODES_PER_SECTOR; if (block_read(location, sector) != 0) memset(sector, 0, sizeof(sector)); memcpy(sector + (number % SBFS_INODES_PER_SECTOR) * SBFS_INODE_SIZE, inode, sizeof(*inode)); return block_write(location, sector); }
static int write_super(void) { uint8_t sector[SBFS_BLOCK_SIZE]; memset(sector, 0, sizeof(sector)); memcpy(sector, &superblock, sizeof(superblock)); return block_write(SBFS_BASE_SECTOR, sector); }
static int name_equal(const char *a, const char *b) { for (uint32_t i = 0; i < SBFS_NAME_MAX; i++) { if (a[i] != b[i]) return 0; if (a[i] == 0) return 1; } return 1; }
static void path_part(const char **cursor, char *part) { while (**cursor == '/') (*cursor)++; uint32_t i = 0; while (**cursor && **cursor != '/' && i < SBFS_NAME_MAX) part[i++] = *(*cursor)++; part[i] = 0; }
static int child(uint32_t parent, const char *name, uint32_t *number, sbfs_inode_t *inode) { for (uint32_t i = 1; i < superblock.inode_count; i++) { sbfs_inode_t candidate; if (read_inode(i, &candidate) != 0) continue; if ((candidate.flags & SBFS_FLAG_USED) != 0 && candidate.parent == parent && name_equal(candidate.name, name)) { if (number) *number = i; if (inode) *inode = candidate; return 0; } } return -1; }
static uint64_t alloc_block(void) { if (superblock.data_next >= superblock.total_sectors - SBFS_BASE_SECTOR) return 0; uint64_t block = superblock.data_next++; write_super(); return block; }
static uint64_t block_for(sbfs_inode_t *inode, uint64_t index, int create) { uint8_t sector[SBFS_BLOCK_SIZE]; uint64_t *p; if (index < 8) { if (inode->direct[index] == 0 && create) inode->direct[index] = alloc_block(); return inode->direct[index]; } index -= 8; if (index < 64) { if (inode->indirect == 0 && create) { inode->indirect = alloc_block(); memset(sector, 0, sizeof(sector)); block_write(SBFS_BASE_SECTOR + inode->indirect, sector); } if (inode->indirect == 0) return 0; if (block_read(SBFS_BASE_SECTOR + inode->indirect, sector) != 0) return 0; p = (uint64_t *)sector; if (p[index] == 0 && create) { p[index] = alloc_block(); block_write(SBFS_BASE_SECTOR + inode->indirect, sector); } return p[index]; } index -= 64; if (index >= 64 * 64) return 0; uint64_t first = index / 64; uint64_t second = index % 64; if (inode->double_indirect == 0 && create) { inode->double_indirect = alloc_block(); memset(sector, 0, sizeof(sector)); block_write(SBFS_BASE_SECTOR + inode->double_indirect, sector); } if (inode->double_indirect == 0 || block_read(SBFS_BASE_SECTOR + inode->double_indirect, sector) != 0) return 0; p = (uint64_t *)sector; if (p[first] == 0 && create) { p[first] = alloc_block(); block_write(SBFS_BASE_SECTOR + inode->double_indirect, sector); memset(sector, 0, sizeof(sector)); block_write(SBFS_BASE_SECTOR + p[first], sector); } if (p[first] == 0 || block_read(SBFS_BASE_SECTOR + p[first], sector) != 0) return 0; p = (uint64_t *)sector; if (p[second] == 0 && create) { p[second] = alloc_block(); block_write(SBFS_BASE_SECTOR + p[first], sector); } return p[second]; }
void sbfs_init(void) { mounted = 0; uint8_t sector[SBFS_BLOCK_SIZE]; if (block_read(SBFS_BASE_SECTOR, sector) != 0) { uart_puts("[ ERR ] SBFS root disk read failed\n"); return; } memcpy(&superblock, sector, sizeof(superblock)); if (superblock.magic != SBFS_MAGIC || superblock.version != SBFS_VERSION || superblock.block_size != SBFS_BLOCK_SIZE || superblock.inode_size != SBFS_INODE_SIZE || superblock.root_inode == 0) { uart_puts("[ ERR ] SBFS superblock not found\n"); return; } mounted = 1; uart_puts("[ OK ] SBFS mounted on /, inodes: "); uart_put_dec(superblock.inode_count); uart_puts("\n"); }
int sbfs_mounted(void) { return mounted; }
int sbfs_lookup(const char *path, uint32_t *inode_number, sbfs_inode_t *inode) { if (!mounted || path == 0 || path[0] != '/') return -1; uint32_t current = superblock.root_inode; sbfs_inode_t current_inode; if (read_inode(current, &current_inode) != 0) return -1; const char *cursor = path; char part[64]; while (1) { path_part(&cursor, part); if (part[0] == 0) break; if ((current_inode.mode & 0170000) != SBFS_MODE_DIR) return -1; if (child(current, part, &current, &current_inode) != 0) return -1; if ((current_inode.mode & 0170000) == SBFS_MODE_LNK) { if (sbfs_lookup(current_inode.symlink, &current, &current_inode) != 0) return -1; } } if (inode_number) *inode_number = current; if (inode) *inode = current_inode; return 0; }
int sbfs_read(uint32_t number, sbfs_inode_t *inode, uint64_t offset, void *buffer, uint64_t size) { (void)number; if (!inode || !buffer || offset >= inode->size) return 0; if (size > inode->size - offset) size = inode->size - offset; uint8_t sector[SBFS_BLOCK_SIZE]; uint8_t *out = buffer; uint64_t done = 0; while (done < size) { uint64_t index = (offset + done) / SBFS_BLOCK_SIZE; uint64_t inside = (offset + done) % SBFS_BLOCK_SIZE; uint64_t block = block_for(inode, index, 0); if (block == 0 || block_read(SBFS_BASE_SECTOR + block, sector) != 0) break; uint64_t count = SBFS_BLOCK_SIZE - inside; if (count > size - done) count = size - done; memcpy(out + done, sector + inside, count); done += count; } return done; }
int sbfs_write(uint32_t number, sbfs_inode_t *inode, uint64_t offset, const void *buffer, uint64_t size) { if (!inode || !buffer || offset > SBFS_MAX_FILE_SIZE || size > SBFS_MAX_FILE_SIZE - offset) return -1; uint8_t sector[SBFS_BLOCK_SIZE]; const uint8_t *in = buffer; uint64_t done = 0; while (done < size) { uint64_t index = (offset + done) / SBFS_BLOCK_SIZE; uint64_t inside = (offset + done) % SBFS_BLOCK_SIZE; uint64_t block = block_for(inode, index, 1); if (block == 0) break; if (inside != 0 || size - done < SBFS_BLOCK_SIZE) { if (block_read(SBFS_BASE_SECTOR + block, sector) != 0) memset(sector, 0, sizeof(sector)); } uint64_t count = SBFS_BLOCK_SIZE - inside; if (count > size - done) count = size - done; memcpy(sector + inside, in + done, count); if (block_write(SBFS_BASE_SECTOR + block, sector) != 0) break; done += count; } if (offset + done > inode->size) inode->size = offset + done; if (inode->start == 0 && done != 0) inode->start = block_for(inode, offset / SBFS_BLOCK_SIZE, 0); if (done != 0) inode->end = block_for(inode, (offset + done - 1) / SBFS_BLOCK_SIZE, 0); write_inode(number, inode); return done; }
static int parent_of(const char *path, uint32_t *parent, char *name) { if (!path || path[0] != '/') return -1; char copy[256]; uint32_t length = 0; while (path[length] && length < sizeof(copy) - 1) { copy[length] = path[length]; length++; } copy[length] = 0; while (length > 1 && copy[length - 1] == '/') copy[--length] = 0; int32_t slash = -1; for (uint32_t i = 1; i < length; i++) if (copy[i] == '/') slash = i; if (slash < 0) { *parent = superblock.root_inode; memcpy(name, copy + 1, length - 1); name[length - 1] = 0; return 0; } copy[slash] = 0; memcpy(name, copy + slash + 1, length - slash - 1); name[length - slash - 1] = 0; return sbfs_lookup(copy, parent, 0); }
int sbfs_create(const char *path, uint32_t mode, uint32_t *number, sbfs_inode_t *inode) { uint32_t parent; char name[64]; if (parent_of(path, &parent, name) != 0 || name[0] == 0 || child(parent, name, 0, 0) == 0 || superblock.inode_count >= SBFS_MAX_INODES) return -1; uint32_t id = superblock.inode_count++; sbfs_inode_t value; memset(&value, 0, sizeof(value)); value.mode = mode; value.flags = SBFS_FLAG_USED; value.links = 1; value.parent = parent; memcpy(value.name, name, sizeof(value.name)); if (write_inode(id, &value) != 0 || write_super() != 0) return -1; if (number) *number = id; if (inode) *inode = value; return 0; }
int sbfs_mkdir(const char *path, uint32_t mode) { return sbfs_create(path, SBFS_MODE_DIR | (mode & 0777), 0, 0); }
int sbfs_unlink(const char *path) { uint32_t id; sbfs_inode_t inode; if (sbfs_lookup(path, &id, &inode) != 0 || id == superblock.root_inode) return -1; inode.flags = 0; inode.links = 0; return write_inode(id, &inode); }
int sbfs_symlink(const char *target, const char *path) { uint32_t id; sbfs_inode_t inode; if (sbfs_create(path, SBFS_MODE_LNK | 0777, &id, &inode) != 0) return -1; uint32_t i = 0; while (target[i] && i < SBFS_SYMLINK_MAX) { inode.symlink[i] = target[i]; i++; } inode.symlink[i] = 0; inode.size = i; return write_inode(id, &inode); }
int sbfs_readlink(const char *path, char *buffer, uint64_t size) { uint32_t id; sbfs_inode_t inode; if (sbfs_lookup(path, &id, &inode) != 0 || (inode.mode & 0170000) != SBFS_MODE_LNK || size == 0) return -1; uint64_t length = inode.size < size - 1 ? inode.size : size - 1; memcpy(buffer, inode.symlink, length); buffer[length] = 0; return length; }
